---
title: Landing Page
timezone: UTC
collections:
  Feedback:
    title: Feedback
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdow: redcarpet
exclude:
- readme.md
- x.html
