---
title: Landing Page
timezone: UTC
collections:
  Feedback:
    title: Feedback
    output: false
markdow: redcarpet
exclude:
- readme.md
- x.html
# plugins:
# - jekyll-paginate
# paginate: 1
# paginate_path: "/preview/:num/"
