---
title: Landing Page
timezone: UTC
collections:
  Reviews:
    title: Reviews
    output: false
markdow: redcarpet
exclude:
- readme.md
- x.html
# plugins:
# - jekyll-paginate
# paginate: 1
# paginate_path: "/preview/:num/"
